### PR TITLE
Include request data as context

### PR DESCRIPTION
**Pull request by mponizil**
Hi there, thanks for this middleware.

Perhaps there's better solution, but it seems like `captureException` could include some request data along with the error object the same way that `Raven.requestHandler()` does. Raven will pick from a few things off a `request` parameter by default:

From https://docs.sentry.io/clients/node/usage/:

> **request**

> Alias: `req`. The `request` object associated with this event, from a Node http server, Express, Koa, or similar. Will be parsed for request details and user context from `request.user` if present. It will only pull out the data that’s handled by the server: `headers`, `method`, `host`, `protocol`, `url`, `query`, `cookies`, `body`, `ip` and `user`.

### CODE REVIEW

**Comment by maticzav** [comment]
Wow! This is soo cool! I love the addition 🎉

Maybe we could include `parent` and `arguments` as well?

**Comment by mponizil** [comment]
Hmm, I'm not sure if those would plug in out of the box as there are a few explicit fields listed under [Additional Data](https://github.com/getsentry/raven-js/blob/master/packages/raven-node/lib/client.js#L552). And I think you would generally be able to gather that information from `request.body`?

I'd need to play around with it to have a stronger understanding but unfortunately don't have the bandwidth right now!

**Comment by maticzav** [comment]
Ah yes, I see. No problem, I'll merge it right away as it seems like a great addition in both cases. 

Thanks 🍻

**Pull request merged**
